# Generated by Django 5.2.14 on 2026-06-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_question_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade_point',
            field=models.IntegerField(max_length=100),
        ),
    ]
