# Generated by Django 5.2.14 on 2026-06-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_alter_question_grade_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade_point',
            field=models.IntegerField(),
        ),
    ]
